# Generated by Django 2.2.4 on 2019-10-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='pagoPeluquero',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
