# Generated by Django 2.2.4 on 2019-10-18 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_venta_pagopeluquero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='corte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salonCorte.Corte'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tintura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salonCorte.Tintura'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipoPago',
            field=models.CharField(blank=True, choices=[('Efectivo', 'Efectivo'), ('Debito', 'Débito'), ('Credito', 'Crédito'), ('Cuenta', 'Cta. Corriente')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
