# Generated by Django 2.2.4 on 2019-10-24 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salonCorte', '0011_cabina_mano'),
        ('venta', '0005_auto_20191024_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cabina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salonCorte.Cabina'),
        ),
        migrations.AddField(
            model_name='venta',
            name='mano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salonCorte.Mano'),
        ),
    ]
