# Generated by Django 2.2.4 on 2019-11-01 03:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0008_auto_20191030_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sueldo',
            name='peluquero',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persona.Empleado'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(default=datetime.date(2019, 11, 1)),
        ),
    ]
