# Generated by Django 2.2.4 on 2019-11-03 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0009_auto_20191101_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='sueldo',
            name='porcentaje',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(default=datetime.date(2019, 11, 3)),
        ),
    ]
