# Generated by Django 2.2.4 on 2019-11-25 02:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0010_auto_20191103_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sueldo',
            name='adelanto',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sueldo',
            name='pago_semanal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sueldo',
            name='tipo_empleado',
            field=models.CharField(blank=True, choices=[('Peluquero', 'Peluquero'), ('Ayudante', 'Ayudante'), ('Maniquiure', 'Maniquiure'), ('Masajista', 'Masajista')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(default=datetime.date(2019, 11, 24)),
        ),
    ]
