# Generated by Django 2.2.4 on 2019-11-29 02:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0011_auto_20191124_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='pagoPeluqueroCalculo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(default=datetime.date(2019, 11, 28)),
        ),
    ]
