# Generated by Django 2.2.4 on 2019-12-11 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0012_auto_20191128_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(default=datetime.date(2019, 12, 11)),
        ),
    ]
