# Generated by Django 2.2.4 on 2020-01-29 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0014_auto_20191227_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(default=datetime.date(2020, 1, 29)),
        ),
    ]
