# Generated by Django 2.2.4 on 2020-01-31 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0015_auto_20200129_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='cabina',
        ),
        migrations.AddField(
            model_name='venta',
            name='cant_tintura',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(default=datetime.date(2020, 1, 31)),
        ),
    ]
