# Generated by Django 2.2.4 on 2020-02-01 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0018_auto_20200201_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='tratamiento',
        ),
    ]
