# Generated by Django 2.2.4 on 2020-02-01 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salonCorte', '0016_tratamiento'),
        ('venta', '0019_remove_venta_tratamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='tratamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salonCorte.Tratamiento'),
        ),
    ]
