# Generated by Django 2.2.4 on 2019-10-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salonCorte', '0002_color_tintura'),
    ]

    operations = [
        migrations.AddField(
            model_name='tintura',
            name='precio',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
