# Generated by Django 2.2.4 on 2019-10-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salonCorte', '0003_tintura_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='gramo',
            field=models.IntegerField(),
        ),
    ]
