# Generated by Django 2.2.4 on 2019-10-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salonCorte', '0004_auto_20191015_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='color',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='tintura',
            old_name='nombre',
            new_name='marca',
        ),
        migrations.RemoveField(
            model_name='color',
            name='gramo',
        ),
        migrations.RemoveField(
            model_name='color',
            name='marca',
        ),
        migrations.AddField(
            model_name='tintura',
            name='gramo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='tintura',
            name='color',
        ),
        migrations.AddField(
            model_name='tintura',
            name='color',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
