# Generated by Django 2.2.4 on 2019-10-23 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salonCorte', '0005_auto_20191023_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='id',
        ),
        migrations.RemoveField(
            model_name='color',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='color',
            name='precio',
        ),
        migrations.AddField(
            model_name='color',
            name='corte_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='salonCorte.Corte'),
            preserve_default=False,
        ),
    ]
