# Generated by Django 2.2.4 on 2019-10-24 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salonCorte', '0006_auto_20191023_1247'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
    ]
