# Generated by Django 2.2.4 on 2019-10-24 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salonCorte', '0007_delete_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tintura',
            old_name='color',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='tintura',
            name='gramo',
        ),
    ]
