# Generated by Django 2.2.4 on 2019-10-24 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salonCorte', '0008_auto_20191024_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('corte_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='salonCorte.Corte')),
                ('codigo', models.CharField(max_length=50)),
            ],
            bases=('salonCorte.corte',),
        ),
        migrations.RenameField(
            model_name='tintura',
            old_name='nombre',
            new_name='color',
        ),
        migrations.AddField(
            model_name='tintura',
            name='gramo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
