# Generated by Django 2.2.4 on 2019-10-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salonCorte', '0010_auto_20191024_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=70)),
                ('precio', models.FloatField()),
                ('contador', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=70)),
                ('precio', models.FloatField()),
            ],
        ),
    ]
