# Generated by Django 2.2.4 on 2019-10-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salonCorte', '0011_cabina_mano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corte',
            name='precio',
            field=models.FloatField(),
        ),
    ]
