# Generated by Django 2.2.4 on 2019-12-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salonCorte', '0012_auto_20191030_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='mano',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='corte',
            name='decripcion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
