# Generated by Django 2.2.4 on 2020-01-31 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salonCorte', '0014_auto_20191227_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tintura',
            name='gramo',
        ),
    ]
