# Generated by Django 2.2.4 on 2020-01-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salonCorte', '0015_remove_tintura_gramo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('concepto', models.CharField(max_length=70)),
                ('precio', models.FloatField()),
            ],
        ),
    ]
